# Generated by Django 2.2.9 on 2023-01-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230115_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, default='нет группы', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='posts.Group', verbose_name='название группы'),
        ),
    ]
